version: '3.9'

services:
  database:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://your_user:your_password@database:5432/your_database
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
